linters-settings:
  gocyclo:
    min-complexity: 20
  goconst:
    min-len: 8
    min-occurrences: 12
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - emptyFallthrough
      - paramTypeCombine
      - unnamedResult
      - exitAfterDefer
    settings:
      rangeValCopy:
        sizeThreshold: 32
  funlen:
    lines: 150
    statements: 120
  gocognit:
    min-complexity: 35
linters:
  enable-all: true
  disable:
    - maligned
    - nakedret
    - gochecknoglobals
    - errcheck
    - lll
    - gochecknoinits
    - dupl
    - goconst
    - interfacer
    - wsl
  fast: false
issues:
  max-same-issues: 0
  exclude-use-default: true
  exclude:
    - "TLS InsecureSkipVerify may be true"
    - "`noCopy` is unused"
    - "can be `expvar.Var`"
    - "cyclomatic complexity .* of func `TestNodeManager` is high"
    - "cyclomatic complexity .* of func `.*ParseRequestHeaderLine` is high"
    - "cyclomatic complexity .* of func `.*Less` is high"
    - "cyclomatic complexity .* of func `matchStringListFilter` is high"
    - "cyclomatic complexity .* of func `.*String` is high"
    - "G108: Profiling endpoint is automatically exposed"
    - "ptrToRefParam: consider `commandsByPeer' to be of non-pointer type"
    - "cognitive complexity .* of func `ProcessRequests` is high"
    - "cognitive complexity .* of func `.*Request..getDistributedResponse` is high"
    - 'Magic number: 1\D '
    - 'Magic number: 2\D '
    - 'Magic number: 3\D '
    - 'Magic number: 4\D '
    - 'Magic number: 10\D '
    - 'Magic number: 16\D '
    - 'Magic number: 32\D '
    - 'Magic number: 64\D '
    - 'Magic number: 100\D '
    - 'Magic number: 2.23\D '
    - 'Magic number: 200\D '
    - 'Magic number: 400\D '
    - 'Magic number: 502\D '
    - 'Magic number: 1024\D '
    - 'package should be `main_test` instead of `main`'
    - 'err113:'
    - 'Expect WriteFile permissions to be 0600 or less'
    - 'Top level comment should end in a period'
    - 'data.Options.Sub.*_raw_query.*is deeply nested'
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gomnd
