linters-settings:
  gocyclo:
    min-complexity: 20
  goconst:
    min-len: 8
    min-occurrences: 12
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - emptyFallthrough
      - paramTypeCombine
      - unnamedResult
      - exitAfterDefer
    settings:
      rangeValCopy:
        sizeThreshold: 32
  funlen:
    lines: 150
    statements: 100
  gocognit:
    min-complexity: 35
  exhaustive:
    default-signifies-exhaustive: true
  asasalint:
    exclude:
      - append
linters:
  enable-all: true
  disable:
    - maligned
    - nakedret
    - lll
    - gochecknoinits
    - wsl
    - exhaustive
    - gofumpt
    - nlreturn
    - exhaustivestruct
    - exhaustruct
    - errorlint
    - paralleltest
    - godot
    - forbidigo
    - ifshort
    - cyclop
    - forcetypeassert
    - nilerr
    - wastedassign
    - varnamelen
    - contextcheck
    - interfacer
    - golint
    - scopelint
    - nonamedreturns
  fast: false
issues:
  max-same-issues: 0
  exclude-use-default: true
  exclude:
    - "TLS InsecureSkipVerify may be true"
    - "`noCopy` is unused"
    - "can be `expvar.Var`"
    - "cyclomatic complexity .* of func `TestNodeManager` is high"
    - "cyclomatic complexity .* of func `.*ParseRequestHeaderLine` is high"
    - "cyclomatic complexity .* of func `.*Less` is high"
    - "cyclomatic complexity .* of func `matchStringListFilter` is high"
    - "cyclomatic complexity .* of func `.*String` is high"
    - "cyclomatic complexity .* of func `TestRequestKeepalive` is high"
    - "cyclomatic complexity .* of func `appendIndexHostsFromServiceColumns` is high"
    - "cyclomatic complexity .* of func `TestNegate` is high"
    - "G108: Profiling endpoint is automatically exposed"
    - "G114: Use of net/http serve function that has no support for setting timeouts"
    - "ptrToRefParam: consider `commandsByPeer' to be of non-pointer type"
    - "cognitive complexity .* of func `ProcessRequests` is high"
    - "cognitive complexity .* of func `.*Request..getDistributedResponse` is high"
    - "cognitive complexity .* of func `.*Peer..waitcondition` is high"
    - "cognitive complexity .* of func `appendIndexHostsFromServiceColumns` is high"
    - "cognitive complexity .* of func `.*..optimizeStatsGroups` is high"
    - 'Magic number: 1\D '
    - 'Magic number: 2\D '
    - 'Magic number: 3\D '
    - 'Magic number: 4\D '
    - 'Magic number: 10\D '
    - 'Magic number: 16\D '
    - 'Magic number: 32\D '
    - 'Magic number: 64\D '
    - 'Magic number: 100\D '
    - 'Magic number: 200\D '
    - 'Magic number: 400\D '
    - 'Magic number: 502\D '
    - 'Magic number: 1024\D '
    - 'Magic number: 0o644\D '
    - 'Magic number: 65536\D '
    - 'package should be `main_test` instead of `main`'
    - 'err113:'
    - 'Expect WriteFile permissions to be 0600 or less'
    - 'Top level comment should end in a period'
    - 'data.Options.Sub.*_raw_query.*is deeply nested'
    - 'missing cases in switch of type SortDirection: _'
    - 'missing cases in switch of type GroupOperator: _'
    - 'missing cases in switch of type Operator: _'
    - 'lines are duplicate of.*_test.go:'
    - 'lines are duplicate of.*objects.go:'
    - "Function 'NewHostsTable' has too many statements"
    - "Function 'NewServicesTable' has too many statements"
    - "func .*noCopy.* is unused"
    - "Use of weak random number generator"
    - "Error return value of `log.Output` is not checked"
    - "prom.* is a global variable"
    - "Build is a global variable"
    - "log is a global variable"
    - "once is a global variable"
    - "empty.* is a global variable"
    - "Objects is a global variable"
    - "CompressionLevel is a global variable"
    - "CompressionMinimumSize is a global variable"
    - "defaultParseOptimizer is a global variable"
    - "VirtualColumnMap is a global variable"
    - "VirtualColumnList is a global variable"
    - "OptionalFlagsStrings is a global variable"
    - "LogFormat is a global variable"
    - "_checkErr contains underscore"
    - "_checkErr2 contains underscore"
    - "(RLIMIT_NOFILE|O_APPEND|O_WRONLY|O_CREATE) contains underscore"
    - "dedup is a global variable"
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gomnd
    - path: config\.go
      linters:
        - gomnd
