version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - funcorder
    - gochecknoglobals
    - gochecknoinits
    - godoclint
    - nonamedreturns
    - noinlineerr
    - paralleltest
    - perfsprint
    - tagliatelle
    - testpackage
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    asasalint:
      exclude:
        - append
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 150
      statements: 100
    gocognit:
      min-complexity: 35
    goconst:
      min-len: 8
      min-occurrences: 12
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
    gocyclo:
      min-complexity: 21
    gomoddirectives:
      replace-local: true
    govet:
      enable-all: true
      settings:
        printf:
          funcs:
            - Tracef
            - Infof
            - Warnf
            - Errorf
            - Fatalf
            - Criticalf
            - Panicf
    lll:
      line-length: 175
  exclusions:
    #warn-unused: true
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupword
          - errcheck
          - errorlint
          - forcetypeassert
          - funlen
          - lll
          - mnd
          - musttag
          - prealloc
        path: _test.*\.go
      - path: (.+)\.go$
        text: Expect WriteFile permissions to be 0600 or less
      - path: (.+)\.go$
        text: 'lines are duplicate of.*_test.go:'
      - path: (.+)\.go$
        text: 'lines are duplicate of.*objects.go:'
      - path: (.+)\.go$
        text: 'Magic number: 0o644\D '
      - path: (.+)\.go$
        text: 'Magic number: 5\D '
      - path: (.+)\.go$
        text: 'Magic number: 7\D '
      - path: (.+)\.go$
        text: 'Magic number: 10\D '
      - path: (.+)\.go$
        text: 'Magic number: 100\D '
      - path: (.+)\.go$
        text: 'Magic number: 1024\D '
      - path: (.+)\.go$
        text: 'Magic number: 16\D '
      - path: (.+)\.go$
        text: 'Magic number: 2\D '
      - path: (.+)\.go$
        text: 'Magic number: 200\D '
      - path: (.+)\.go$
        text: 'Magic number: 3\D '
      - path: (.+)\.go$
        text: 'Magic number: 30\D '
      - path: (.+)\.go$
        text: 'Magic number: 4\D '
      - path: (.+)\.go$
        text: 'Magic number: 60\D '
      - path: (.+)\.go$
        text: 'Magic number: 120\D '
      - path: (.+)\.go$
        text: 'Magic number: 1800\D '
      - path: (.+)\.go$
        text: 'Magic number: 65536\D '
      - path: (.+)\.go$
        text: cognitive complexity .* of func `.*Request..getDistributedResponse` is high
      - path: (.+)\.go$
        text: cognitive complexity .* of func `.*appendIndexHostsFromServiceColumns` is high
      - path: (.+)\.go$
        text: cognitive complexity .* of func `prepareTmpDataHostService` is high
      - path: (.+)\.go$
        text: cognitive complexity .* of func `.*RawResultSet..Less` is high
      - path: (.+)\.go$
        text: cyclomatic complexity .* of func `.*ParseRequestHeaderLine` is high
      - path: (.+)\.go$
        text: cyclomatic complexity .* of func `.*appendIndexHostsFromServiceColumns` is high
      - path: (.+)\.go$
        text: Error return value of `log.Output` is not checked
      - path: (.+)\.go$
        text: Function 'NewHostsTable' has too many statements
      - path: (.+)\.go$
        text: Function 'NewServicesTable' has too many statements
      - path: (.+)\.go$
        text: 'G114: Use of net/http serve function that has no support for setting timeouts'
      - path: (.+)\.go$
        text: 'ptrToRefParam: consider `commandsByPeer'' to be of non-pointer type'
      - path: (.+)\.go$
        text: TLS InsecureSkipVerify may be true
      - path: (.+)\.go$
        text: Use of weak random number generator
      - path: (.+)\.go$
        text: LogPrefixer.*does not support error-wrapping
      - path: (.+)\.go$
        text: constant name 'Or' is too short
      - path: (.+)\.go$
        text: variable name 'ok' is too short
      - path: (.+)\.go$
        text: 'fmtappendf:'
      - path: (.+)\.go$
        text: 'must not be called. use'
      - path: (.+)\.go$
        text: 'Goroutine creation can be simplified using WaitGroup.Go'
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
