version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - funcorder
    - gochecknoglobals
    - gochecknoinits
    - godoclint
    - nonamedreturns
    - noinlineerr
    - paralleltest
    - perfsprint
    - tagliatelle
    - testpackage
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    asasalint:
      exclude:
        - append
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 150
      statements: 100
    gocognit:
      min-complexity: 35
    goconst:
      min-len: 8
      min-occurrences: 12
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
    gocyclo:
      min-complexity: 21
    gomoddirectives:
      replace-local: true
    govet:
      enable-all: true
      settings:
        printf:
          funcs:
            - Tracef
            - Infof
            - Warnf
            - Errorf
            - Fatalf
            - Criticalf
            - Panicf
    lll:
      line-length: 175
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupword
          - errcheck
          - errorlint
          - forcetypeassert
          - funlen
          - lll
          - mnd
          - musttag
        path: _test.*\.go
      - path: (.+)\.go$
        text: data.Options.Sub.*_raw_query.*is deeply nested
      - path: (.+)\.go$
        text: Expect WriteFile permissions to be 0600 or less
      - path: (.+)\.go$
        text: 'lines are duplicate of.*_test.go:'
      - path: (.+)\.go$
        text: 'lines are duplicate of.*objects.go:'
      - path: (.+)\.go$
        text: 'Magic number: 0o644\D '
      - path: (.+)\.go$
        text: 'Magic number: 1\D '
      - path: (.+)\.go$
        text: 'Magic number: 5\D '
      - path: (.+)\.go$
        text: 'Magic number: 7\D '
      - path: (.+)\.go$
        text: 'Magic number: 10\D '
      - path: (.+)\.go$
        text: 'Magic number: 100\D '
      - path: (.+)\.go$
        text: 'Magic number: 1024\D '
      - path: (.+)\.go$
        text: 'Magic number: 16\D '
      - path: (.+)\.go$
        text: 'Magic number: 2\D '
      - path: (.+)\.go$
        text: 'Magic number: 200\D '
      - path: (.+)\.go$
        text: 'Magic number: 3\D '
      - path: (.+)\.go$
        text: 'Magic number: 30\D '
      - path: (.+)\.go$
        text: 'Magic number: 32\D '
      - path: (.+)\.go$
        text: 'Magic number: 4\D '
      - path: (.+)\.go$
        text: 'Magic number: 60\D '
      - path: (.+)\.go$
        text: 'Magic number: 64\D '
      - path: (.+)\.go$
        text: 'Magic number: 120\D '
      - path: (.+)\.go$
        text: 'Magic number: 1800\D '
      - path: (.+)\.go$
        text: 'Magic number: 65536\D '
      - path: (.+)\.go$
        text: 'missing cases in switch of type GroupOperator: _'
      - path: (.+)\.go$
        text: 'missing cases in switch of type Operator: _'
      - path: (.+)\.go$
        text: 'missing cases in switch of type SortDirection: _'
      - path: (.+)\.go$
        text: package should be `main_test` instead of `main`
      - path: (.+)\.go$
        text: Top level comment should end in a period
      - path: (.+)\.go$
        text: _checkErr contains underscore
      - path: (.+)\.go$
        text: _checkErr2 contains underscore
      - path: (.+)\.go$
        text: (RLIMIT_NOFILE|O_APPEND|O_WRONLY|O_CREATE) contains underscore
      - path: (.+)\.go$
        text: '`noCopy` is unused'
      - path: (.+)\.go$
        text: Build is a global variable
      - path: (.+)\.go$
        text: can be `expvar.Var`
      - path: (.+)\.go$
        text: cognitive complexity .* of func `.*..optimizeStatsGroups` is high
      - path: (.+)\.go$
        text: cognitive complexity .* of func `.*Peer..waitcondition` is high
      - path: (.+)\.go$
        text: cognitive complexity .* of func `.*Request..getDistributedResponse` is high
      - path: (.+)\.go$
        text: cognitive complexity .* of func `.*appendIndexHostsFromServiceColumns` is high
      - path: (.+)\.go$
        text: cognitive complexity .* of func `ProcessRequests` is high
      - path: (.+)\.go$
        text: cognitive complexity .* of func `prepareTmpDataHostService` is high
      - path: (.+)\.go$
        text: cognitive complexity .* of func `.*RawResultSet..Less` is high
      - path: (.+)\.go$
        text: CompressionLevel is a global variable
      - path: (.+)\.go$
        text: CompressionMinimumSize is a global variable
      - path: (.+)\.go$
        text: cyclomatic complexity .* of func `.*Less` is high
      - path: (.+)\.go$
        text: cyclomatic complexity .* of func `.*ParseRequestHeaderLine` is high
      - path: (.+)\.go$
        text: cyclomatic complexity .* of func `.*String` is high
      - path: (.+)\.go$
        text: cyclomatic complexity .* of func `.*appendIndexHostsFromServiceColumns` is high
      - path: (.+)\.go$
        text: cyclomatic complexity .* of func `matchStringListFilter` is high
      - path: (.+)\.go$
        text: cyclomatic complexity .* of func `TestNegate` is high
      - path: (.+)\.go$
        text: cyclomatic complexity .* of func `TestNodeManager` is high
      - path: (.+)\.go$
        text: cyclomatic complexity .* of func `TestRequestKeepalive` is high
      - path: (.+)\.go$
        text: cyclomatic complexity .* of func `.*statusSet` is high
      - path: (.+)\.go$
        text: cyclomatic complexity .* of func `.*statusGet` is high
      - path: (.+)\.go$
        text: dedup is a global variable
      - path: (.+)\.go$
        text: defaultParseOptimizer is a global variable
      - path: (.+)\.go$
        text: empty.* is a global variable
      - path: (.+)\.go$
        text: Error return value of `log.Output` is not checked
      - path: (.+)\.go$
        text: func .*noCopy.* is unused
      - path: (.+)\.go$
        text: Function 'NewHostsTable' has too many statements
      - path: (.+)\.go$
        text: Function 'NewServicesTable' has too many statements
      - path: (.+)\.go$
        text: 'G108: Profiling endpoint is automatically exposed'
      - path: (.+)\.go$
        text: 'G114: Use of net/http serve function that has no support for setting timeouts'
      - path: (.+)\.go$
        text: log is a global variable
      - path: (.+)\.go$
        text: LogFormat is a global variable
      - path: (.+)\.go$
        text: Objects is a global variable
      - path: (.+)\.go$
        text: once is a global variable
      - path: (.+)\.go$
        text: OptionalFlagsStrings is a global variable
      - path: (.+)\.go$
        text: prom.* is a global variable
      - path: (.+)\.go$
        text: 'ptrToRefParam: consider `commandsByPeer'' to be of non-pointer type'
      - path: (.+)\.go$
        text: TLS InsecureSkipVerify may be true
      - path: (.+)\.go$
        text: Use of weak random number generator
      - path: (.+)\.go$
        text: VirtualColumnList is a global variable
      - path: (.+)\.go$
        text: VirtualColumnMap is a global variable
      - path: (.+)\.go$
        text: LogPrefixer.*does not support error-wrapping
      - path: (.+)\.go$
        text: constant name 'Or' is too short
      - path: (.+)\.go$
        text: variable name 'ok' is too short
      - path: (.+)\.go$
        text: 'fmtappendf:'
      - path: (.+)\.go$
        text: 'must not be called. use'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
