linters-settings:
  gocyclo:
    min-complexity: 20
  goconst:
    min-len: 8
    min-occurrences: 12
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - emptyFallthrough
      - paramTypeCombine
      - unnamedResult
      - exitAfterDefer
    settings:
      rangeValCopy:
        sizeThreshold: 32
  funlen:
    lines: 150
    statements: 120
linters:
  enable-all: true
  disable:
    - maligned
    - nakedret
    - gochecknoglobals
    - errcheck
    - lll
    - gochecknoinits
    - dupl
    - goconst
  fast: false
issues:
  max-same-issues: 0
  exclude-use-default: true
  exclude:
    - "TLS InsecureSkipVerify may be true"
    - "`noCopy` is unused"
    - "can be `expvar.Var`"
    - "cyclomatic complexity .* of func `TestNodeManager` is high"
    - "cyclomatic complexity .* of func `.*ParseRequestHeaderLine` is high"
    - "cyclomatic complexity .* of func `.*Less` is high"
    - "cyclomatic complexity .* of func `matchStringListFilter` is high"
    - "cyclomatic complexity .* of func `.*String` is high"
