// Code generated by "stringer -type=DataType"; DO NOT EDIT.

package lmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StringCol-1]
	_ = x[StringListCol-2]
	_ = x[StringListSortedCol-3]
	_ = x[IntCol-4]
	_ = x[Int64Col-5]
	_ = x[Int64ListCol-6]
	_ = x[FloatCol-7]
	_ = x[JSONCol-8]
	_ = x[CustomVarCol-9]
	_ = x[ServiceMemberListCol-10]
	_ = x[InterfaceListCol-11]
	_ = x[StringLargeCol-12]
}

const _DataType_name = "StringColStringListColStringListSortedColIntColInt64ColInt64ListColFloatColJSONColCustomVarColServiceMemberListColInterfaceListColStringLargeCol"

var _DataType_index = [...]uint8{0, 9, 22, 41, 47, 55, 67, 75, 82, 94, 114, 130, 144}

func (i DataType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_DataType_index)-1 {
		return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataType_name[_DataType_index[idx]:_DataType_index[idx+1]]
}
