// Code generated by "stringer -type=FetchType"; DO NOT EDIT.

package lmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Static-1]
	_ = x[Dynamic-2]
	_ = x[None-3]
}

const _FetchType_name = "StaticDynamicNone"

var _FetchType_index = [...]uint8{0, 6, 13, 17}

func (i FetchType) String() string {
	i -= 1
	if i >= FetchType(len(_FetchType_index)-1) {
		return "FetchType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _FetchType_name[_FetchType_index[i]:_FetchType_index[i+1]]
}
