// Code generated by "stringer -type=StorageType"; DO NOT EDIT.

package lmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LocalStore-1]
	_ = x[RefStore-2]
	_ = x[VirtualStore-3]
}

const _StorageType_name = "LocalStoreRefStoreVirtualStore"

var _StorageType_index = [...]uint8{0, 10, 18, 30}

func (i StorageType) String() string {
	i -= 1
	if i >= StorageType(len(_StorageType_index)-1) {
		return "StorageType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _StorageType_name[_StorageType_index[i]:_StorageType_index[i+1]]
}
