name: e2e test
on:
  push:
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: './go.mod'
    - run: make clean
    - run: make
    - run: make test-e2e
